### PR TITLE
Changes to img tag and style path

### PR DESCRIPTION
**Pull request by Juveria-Dalvi**
Watch the path of your scss file and also use period (.)

### CODE REVIEW

**Comment by JuveriaD** [comment]
Check the path of scss file once

**Comment by JuveriaD** [comment]
Check your path of style sheet

**Comment by JuveriaD** [comment]
I don't get why your style sheet isn't working image's are set on display now after changes

**Comment by JuveriaD** [comment]
h

**Comment by Juveria-Dalvi** [comment]
.

**Pull request closed without merging**
